"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class PTN:
    def __init__(self) -> None:
        ...
    
    def parse(self, name):
        ...
    


